server:
  port: 2333
  address: 0.0.0.0
  http2:
    enabled: true

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:02f536d9ac05b4bb0f91dedc19f964f30fc18559"
      snapshot: true
  server:
    password: "youshallnotpass"
    sources:
      youtube: false # Disable built-in source, let the plugin handle it
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingIntervalMs: 20
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    oauth:
      enabled: true
      refreshToken: "${YOUTUBE_REFRESH_TOKEN:}"
      skipInitialization: false
    clients:
      - TVHTML5
      - MUSIC
      - IOS
      - ANDROID_MUSIC
      - WEB
    clientOptions:
      TVHTML5:
        playback: true
        videoLoading: true
        searching: false
        playlistLoading: true
      IOS:
        playback: true
        videoLoading: true
        searching: false
        playlistLoading: true
      MUSIC:
        playback: false
        videoLoading: false
        searching: true
        playlistLoading: true

logging:
  file:
    path: ./logs/

  level:
    root: INFO
    lavalink: INFO
    dev.lavalink.youtube: DEBUG

  request:
    enabled: true
    includeHeaders: false
    includePayload: true
    maxPayloadLength: 10000
